dirs.src = "src"
dirs.out = "out"
dirs.static = "static"
dirs.layout = "layout"

[data]
name = "world"
software = { name = "mksite", version = "0.1.0" }

[processors]
md.html = "pandoc -f markdown -t html"
