dirs.src = "src"
dirs.out = "out"
dirs.static = "static"
dirs.layout = "layout"

[data]
name = "world"
software = { name = "mksite", version = "0.1.0" }

[transforms]
md.html = "pandoc -f markdown -t html"
scd.html = ["scdoc", "pandoc -f man -t html"]
scd.pdf = ["scdoc", "pandoc -f man -t pdf"]
