[package]
name = "mksite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.14", features = ["derive"] }
fs_extra = "1.2.0"
maplit = "1.0.2"
serde = { version = "1.0.145", features = ["derive"] }
tera = "1.17.1"
toml = "0.5.9"
