[package]
name = "mksite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.14", features = ["derive"] }
maplit = "1.0.2"
ramhorns = {version = "0.14.0", default_features = false}
serde = { version = "1.0.145", features = ["derive"] }
toml = "0.5.9"
