# Default directory names.
dirs.src = "src"       # The src directory contains all site content to be processed.
dirs.out = "out"       # The out directory is where the generated site is written to.
dirs.static = "static" # Content in the static directory is copied as-is to the out directory.
dirs.layout = "layout" # The layout directory is where layouts live.

# The contents of the data section are made available in template rendering.
[data]
# foo = "bar"

# Processors are used to further transform content after applying templating.
[processors]
# md.html = "pandoc -f markdown -t html"
