# The contents of the data section are made available in template rendering.
[data]
# foo = "bar"

# Transforms are used to further transform content after template rendering.
[transforms]
# md.html = "pandoc -f markdown -t html"
